---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/portfolio
  label: Portfolio
  create: all
  match: "**/*"
  templates:
  - gallery-7dd5227b-b779-4471-9c83-fb0bdd508f9f
- type: directory
  path: content/journal
  label: Journal
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.50'
